# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

proximalGraph <- function(U, grp, grpV, etaG, regul, lam1, lam2 = 0.0, lam3 = 0.0, num_threads = -1L, intercept = FALSE, resetflow = FALSE, verbose = FALSE, pos = FALSE, clever = TRUE, eval = TRUE, size_group = 1L, transpose = FALSE) {
    .Call(`_mtool_proximalGraph`, U, grp, grpV, etaG, regul, lam1, lam2, lam3, num_threads, intercept, resetflow, verbose, pos, clever, eval, size_group, transpose)
}

lik <- function(betas, covariates, Id, Event, Fup, Start, Stop) {
    .Call(`_mtool_lik`, betas, covariates, Id, Event, Fup, Start, Stop)
}

der_lik <- function(betas, covariates, Id, Event, Fup, Start, Stop) {
    .Call(`_mtool_der_lik`, betas, covariates, Id, Event, Fup, Start, Stop)
}

SurvGraphSelect <- function(covariates, Id, Event, Fup, Start, Stop, grp, grpV, etaG, regul, betas, t, alpha, epsilon, lam1, lam2 = 0.0, lam3 = 0.0, num_threads = -1L, intercept = FALSE, resetflow = FALSE, verbose = FALSE, pos = FALSE, clever = TRUE, eval = TRUE, size_group = 1L, transpose = FALSE) {
    .Call(`_mtool_SurvGraphSelect`, covariates, Id, Event, Fup, Start, Stop, grp, grpV, etaG, regul, betas, t, alpha, epsilon, lam1, lam2, lam3, num_threads, intercept, resetflow, verbose, pos, clever, eval, size_group, transpose)
}

